### ISSUE TITLE
New openstreetmap-carto release, v3.3.1

### ISSUE THREAD

**Issue by math1985** [openstreetmap/chef#124] opened 2017-05-22 17:34 UTC
A new version of openstreetmap-carto, [v3.3.1](https://github.com/gravitystorm/openstreetmap-carto/releases/tag/v3.3.1), has been released. 

This version fixes a regression in the rendering of intermittent streams.

**Comment by pnorman** [comment] 2017-05-22 20:42
The changes should only be visible at higher zooms

**Comment by tomhughes** [comment] 2017-05-22 21:34
How important is this? I mean I only just started the 3.3.0 rollout and I wasn't actually planning to do any more 3.x versions...

**Comment by HolgerJeromin** [comment] 2017-05-23 04:44
Intermittent waterways are quite ugly:
https://www.openstreetmap.org/#map=17/51.88003/8.47295

**Comment by pnorman** [comment] 2017-05-23 07:10
> How important is this? I mean I only just started the 3.3.0 rollout and I wasn't actually planning to do any more 3.x versions...

It fixes a regression in intermittent waterways. It shouldn't impact low zoom. I suppose it's a question of how long it takes to switch to 4.0.0. We've tagged it, but haven't put out a release announcement yet.

**Comment by EwenH** [comment] 2017-06-05 13:10
How important. In the desert, it's almost impossible to see the other far more important elements. The users eyes should be on the road to the airport but they have it all focusing on the catchment area of the river in the first URL and zooming in environments like this is not going to help you due to the vastness.

http://www.openstreetmap.org/search?query=alice%20springs#map=13/-22.5156/122.1017
and http://www.openstreetmap.org/search?query=alice%20springs#map=13/-23.9586/132.8977

**Comment by math1985** [comment] 2017-06-19 13:46
Did https://git.openstreetmap.org/chef.git/commit/d693fd0c3241bd96e0a6cd5802d3ea1c937f6943 resolve this issue?

**Comment by tomhughes** [comment] 2017-06-19 13:48
It resolved it for one of the four render servers, yes (well assuming that 4.0.0 has the fix).

**Comment by kocio-pl** [comment] 2017-06-19 16:44
Looks like the fix is there too:

https://github.com/gravitystorm/openstreetmap-carto/commit/102fb1925875dce67a3176284872f8014dc78a1e

Does it mean that vial already renders 4.0.0 styled tiles or database reload is still needed? What about style/database update on other tile servers, are there any estimations when it would be done?

**Comment by tomhughes** [comment] 2017-06-19 16:49
I already confirmed that 4.0.0 has been rolled on out vial. When the rollout is complete I will let you all know by closing this bug - until then please relax a bit.

**Comment by kocio-pl** [comment] 2017-06-19 16:56
I just didn't understand that it was full upgrade and what is the plan, so I asked - no stress involved.

**Comment by tomhughes** [comment] 2017-06-26 07:26
Carto 4.0.0 is now fully deployed.

**Closed by tomhughes** 2017-06-26 07:26 UTC

**Comment by math1985** [comment] 2017-06-26 07:37
Cool, great news!
